// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy3MyraP6ZK3OzF3Rt4djUvxdm_1nqbpQ',
    appId: '1:369656565782:web:0ead13762e0192273de537',
    messagingSenderId: '369656565782',
    projectId: 'telesaludunad-e5240',
    authDomain: 'telesaludunad-e5240.firebaseapp.com',
    storageBucket: 'telesaludunad-e5240.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd0vHEIZaQyUbpZLbzImPMebzwO_VoBK4',
    appId: '1:369656565782:android:31445786682799383de537',
    messagingSenderId: '369656565782',
    projectId: 'telesaludunad-e5240',
    storageBucket: 'telesaludunad-e5240.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8w0epTt47M0XZHXhvRbv7XNs3adsSne0',
    appId: '1:369656565782:ios:fe85e3bfeefcb3a83de537',
    messagingSenderId: '369656565782',
    projectId: 'telesaludunad-e5240',
    storageBucket: 'telesaludunad-e5240.firebasestorage.app',
    iosBundleId: 'com.unad.telesalud.frontend',
  );
}
